{{- if .Values.frontendproxy.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "temporal.fullname" $ }}-frontend-proxy-sa
  namespace: rafay-core
  labels:
    app: temporal-frontend-proxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "temporal.fullname" $ }}-frontend-proxy-role
  namespace: rafay-core
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "temporal.fullname" $ }}-frontend-proxy-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "temporal.fullname" $ }}-frontend-proxy-sa
  namespace: {{ $.Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "temporal.fullname" $ }}-frontend-proxy-role
  apiGroup: rbac.authorization.k8s.io
{{- end }} 