{{- if or $.Values.mongodb.enabled $.Values.mongodb.external.enabled }}
{{- range $store := (list "default" "visibility") }}
{{- if eq (include "temporal.persistence.driver" (list $ $store)) "mongodb" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "temporal.persistence.secretName" (list $ $store) }}
  labels:
    {{- include "temporal.resourceLabels" (list $ (printf "%s-store" $store) "secret") | nindent 4 }}
  annotations:
    {{- include "temporal.resourceAnnotations" (list $ (printf "%s-store" $store) "secret") | nindent 4 }}
type: Opaque
data:
  {{ include "temporal.persistence.secretKey" (list $ $store) }}: {{ include "temporal.persistence.mongodb.password" (list $ $store) | b64enc | quote }}
---
{{- end }}
{{- end }}
{{- end }} 